### ISSUE TITLE
标签页过度时中间夹着一个白色，感觉很奇怪，如图

### ISSUE THREAD

**Issue by HoGafi** [Achuan-2/siyuan-themes-tsundoku-stone#5]
![image](https://user-images.githubusercontent.com/32252229/158764343-0d954682-af8d-430f-8cd6-6c70fb3cab1d.png)

**Comment by Achuan-2** [comment]
感谢反馈，试着改了下https://github.com/Achuan-2/siyuan-themes-tsundoku-stone/commit/b7badb00eb81188d9ebbf07e48836ced5a6ba19a

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/158809064-9d8604c4-878b-4c7a-9791-605b5473b5d2.png)

**Comment by HoGafi** [comment]
![1647528897(1)](https://user-images.githubusercontent.com/32252229/158831369-99740d14-4041-476e-9b83-567235cd5b94.jpg)
这个小缺口和上面的导航栏一个色是不是会更一体些，比如下面Chrome样式就比较一体
![image](https://user-images.githubusercontent.com/32252229/158831578-525cefc0-bf7c-42e3-ae67-a488534e2c4a.png)

**Comment by Achuan-2** [comment]
暂时做不到，chrome标签之间的竖线应该用了伪元素
