### ISSUE TITLE
对搜索结果页面进行全屏展示的 bug

### ISSUE THREAD

**Issue by HildaM** [Achuan-2/siyuan-themes-tsundoku-stone#7]
问题细节：https://ld246.com/article/1655019062383

**Comment by Achuan-2** [comment]
原来搜索页面也可以ctrl+P，学习了，已修复https://github.com/Achuan-2/siyuan-themes-tsundoku-stone/commit/04408423e574467dde4df800846204fd11df1643#diff-fecf2bb3b8ad5f70e3e66c7cb2037039089186ab8d1449fc4c6b7685e3e25750
